#Penas
#GNS3

- hosts: router
  become: true
  gather_facts: no
  tasks:

    - name: Execute the inputted configuration
      cisco.ios.ios_hostname:
        config:
          hostname: R1
        state: merged

    - name: Inputting MOTD
      cisco.ios.ios_banner:
        banner: motd
        text: |
          Unaithorized Personels are Prohibited!
        state: present

    - name: Inputting domain name
      cisco.ios.ios_system:
        domain_name: cisco.com
        state: present

    - name: Configuring Line Console
      cisco.ios.ios_config:
        lines:
        - password cisco
        - login
        - logging synchronous
        parents: line console 0

    - name: Configuring Exec Mode
      cisco.ios.ios_config:
        lines: enable secret class

    - name: Do Copy Run Start
      cisco.ios.ios_config:
        save_when: modified

    - block:

      - name: Ensuring the Configuration by executing show run
        cisco.ios.ios_command:
          commands: show run
        register: output_run

      - debug:
          msg="{{ output_run }}"

