#Penas
#Playbook for Building a CA with SSL

- hosts: all
  become: true
  pre_tasks:

    - name: Update and Upgrade Server1 (Ubuntu)
      apt:
        update_cache: yes
        upgrade: 'yes'
      when: ansible_distribution == "Ubuntu"

    - name: dpkg fixing in Server1 (Ubuntu)
      shell: |
        dpkg --configure -a
      when: ansible_distribution == "Ubuntu"

    - name: install apache2 package
      apt:
        name: apache2

- hosts: servers
  become: true
  tasks:

    - name: Installing OpenSSL
      apt:
        name: openssl
        state: present

    - name: Generate Certificate Authorization key
      openssl_privatekey:
        path: /etc/ssl/private/Cert_A.key
        size: 4096
      register: ca_key

    - name: Generate Certificate Authorization Details
      openssl_csr:
        path: /etc/ssl/certs/Cert_A.csr
        privatekey_path: /etc/ssl/private/ca.key
        common_name: "Certificate Authorization"
        email_address: "qivhpenas@tip.edu.ph"
      register: ca_csr

    - name: Self-sign the Certificate Authorization certificate
      openssl_certificate:
        path: /etc/ssl/certs/Cert_A.crt
        privatekey_path: /etc/ssl/private/Cert_A.key
        csr_path: /etc/ssl/certs/Cert_A.csr
        provider: selfsigned
        force: true

    - name: Copy the CA certificate to clients
      copy:
        src: /etc/ssl/certs/ca-certificates.crt
        dest: /etc/pki/ca-trust/source/anchors/
